services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27067:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro

  # postgres: 
  #   image: timescale/timescaledb:latest-pg16 
  #   container_name: timescaledb 
  #   environment: 
  #     - POSTGRES_USER=admin 
  #     - POSTGRES_PASSWORD=admin123 
  #     - POSTGRES_DB=metricsdb 
  #   ports: 
  #     - "5432:5432" 
  #   volumes: 
  #     - pg_data:/var/lib/postgresql/data 
 
#   influxdb: 
#     image: influxdb:2.7 
#     container_name: influxdb 
#     environment: 
#       - DOCKER_INFLUXDB_INIT_MODE=setup 
#       - DOCKER_INFLUXDB_INIT_USERNAME=admin 
#       - DOCKER_INFLUXDB_INIT_PASSWORD=admin123 
#       - DOCKER_INFLUXDB_INIT_ORG=example-org 
#       - DOCKER_INFLUXDB_INIT_BUCKET=example-bucket 
#     ports: 
#       - "8086:8086" 
#     volumes: 
#       - influx_data:/var/lib/influxdb2 


volumes:
  mongo_data:
  # pg_data:
  # influx_data:
