services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27067:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d:ro


  timescaledb: 
    image: timescale/timescaledb:latest-pg16 
    container_name: timescale-db
    environment:
      - POSTGRES_USER=timescaledb_user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=timescale_db
    ports: 
      - "5467:5432" 
    volumes: 
      - timescale_data:/var/lib/postgresql/data 
      - ./init-timescaledb:/docker-entrypoint-initdb.d 
 

  benchmark_db:    
    image: postgres:16
    container_name: benchmarkdb_db
    environment:
      POSTGRES_USER: benchmarkdb_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: benchmark_db
    ports:
      - "5468:5432"
    volumes:
      - benchmark_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10


 
  influxdb: 
    image: influxdb:2.7 
    container_name: influxdb 
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb 
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123 
      - DOCKER_INFLUXDB_INIT_ORG=example-org 
      - DOCKER_INFLUXDB_INIT_BUCKET=example-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    ports: 
      - "8086:8086" 
    volumes: 
      - influx_data:/var/lib/influxdb2 
      - ./init-influxdb:/docker-entrypoint-initdb.d


volumes:
  mongo_data:
  benchmark_data:
  timescale_data:
  influx_data:
