mongodb:
  MONGO_DB_USER: "{{ env_var('MONGO_DB_USER')}}"
  MONGO_DB_PASSWORD: "{{ env_var('MONGO_DB_PASSWORD')}}"

  # MongoDB Atlas cluster
  MONGO_DB_CLUSTER: "{{ env_var('MONGO_DB_CLUSTER')}}"

  # localhost and container connection details
  MONGO_DB_HOST: "{{ env_var('MONGO_DB_HOST')}}"
  MONGO_DB_PORT: "{{ env_var('MONGO_DB_PORT')}}"

  MONGODB_DATABASE_NAME: "{{ env_var('MONGODB_TIMESERIES_DATABASE_NAME')}}"
  MONGODB_COLLECTION_NAME: "{{ env_var('MONGODB_TIMESERIES_COLLECTION_NAME')}}"

  MONGO_MODE: "{{ env_var('MONGO_MODE')}}"

general:
  data_file: "./data/sample_data.json"
  log_file: "./logs/mongodb_forwarder.log"