postgres:
  POSTGRES_USER: "{{ env_var('POSTGRES_USER')}}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD')}}"
  POSTGRES_DATABASE: "{{ env_var('POSTGRES_DATABASE')}}"
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST')}}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT')}}"
  POSTGRES_SCHEMA: "{{ env_var('POSTGRES_SCHEMA')}}"

general:
  log_file: "./logs/benchmark_db_forwarder.log"