database:
  MONGODB_USER: "{{ env_var('MONGODB_USER')}}"
  MONGODB_PASSWORD: "{{ env_var('MONGODB_PASSWORD')}}"

  # MongoDB Atlas cluster
  MONGODB_CLUSTER: "{{ env_var('MONGODB_CLUSTER')}}"

  # localhost and container connection details
  MONGODB_HOST: "{{ env_var('MONGODB_HOST')}}"
  MONGODB_PORT: "{{ env_var('MONGODB_PORT')}}"

  MONGODB_DATABASE_NAME: "{{ env_var('MONGODB_TIMESERIES_DATABASE_NAME')}}"
  MONGODB_COLLECTION_NAME: "{{ env_var('MONGODB_TIMESERIES_COLLECTION_NAME')}}"

  MONGODB_MODE: "{{ env_var('MONGODB_MODE')}}"

general:
  row_data_file: "./data/sample_data.json"
  mongodb_data_file: "./data/mongodb_data/data_observations_10_20250130_20251221.json"
  mongodb_data_folder_path: "./data/mongodb_data/"
  log_file: "./logs/mongodb_logs.log"
