database:
  INFLUXDB_USERNAME: "{{ env_var('INFLUXDB_USERNAME') }}"
  INFLUXDB_PASSWORD: "{{ env_var('INFLUXDB_PASSWORD') }}"
  INFLUXDB_ORG: "{{ env_var('INFLUXDB_ORG') }}"
  INFLUXDB_BUCKET: "{{ env_var('INFLUXDB_BUCKET') }}"
  INFLUXDB_HOST: "{{ env_var('INFLUXDB_HOST') }}"
  INFLUXDB_PORT: "{{ env_var('INFLUXDB_PORT') }}"
  INFLUXDB_TOKEN: "{{ env_var('INFLUXDB_TOKEN') }}"

general:
  log_file: "./logs/influxdb.log"
  influxdb_data_folder_path: "./data/influxdb_data/"